apiVersion: v1
kind: Service

metadata:
  labels:
    io.kompose.service: product-host
  name: product-host

spec:
  ports:
    - name: "50002"
      port: 50002
      targetPort: 8080
  selector:
    io.kompose.service: product-host
    
status:
  loadBalancer: {}
