apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    io.kompose.service: product-host
  name: product-host

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-host

  template:
    metadata:
      labels:
        io.kompose.network/services-backend: "true"
        io.kompose.service: product-host

    spec:
      containers:
        - name: producthost
         
          env:
            - name: CONNECTION_STRING
              value: '"Server=tcp:productpostgresadmin,5432;Initial Catalog=Product;Persist Security Info=False;User ID=productpostgresadmin;Password=admin;Connection Timeout=30;"'
          
          image: lutrp/goodfood-productms
                    
          resources:
            limits:
              cpu: 100m
              memory: 200Mi

          ports:
            - containerPort: 8080
              hostPort: 50002
