apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-host

spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-host

  template:
    metadata:
      labels:
        app: product-host

    spec:
      containers:
        - name: producthost
         
          env:
            - name: CONNECTION_STRING
              value: 'postgresql://productpostgresadmin:admin@product-postgres-db-service:5500'
            - name: RABBITMQ_URL
              value: amqp://admin:admin@rabbitmq-service:5672/
            - name: GIN_MODE
              value: debug
            - name: LOG_MODE
              value: debug
          image: lutrp/goodfood-productms
          imagePullPolicy: "Always"
                    
          resources:
            limits:
              cpu: 100m
              memory: 200Mi

          ports:
            - containerPort: 8080
