apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-host

spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-host

  template:
    metadata:
      labels:
        app: product-host

    spec:
      containers:
        - name: producthost
         
          env:
            - name: CONNECTION_STRING
              value: '"Server=tcp:product-postgres-db-service,5500;Initial Catalog=Product;Persist Security Info=False;User ID=productpostgresadmin;Password=admin;Connection Timeout=30;"'
          
          image: lutrp/goodfood-productms
                    
          resources:
            limits:
              cpu: 100m
              memory: 200Mi

          ports:
            - containerPort: 8080
