apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  labels:
    io.kompose.service: product
  name: product

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
