apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    io.kompose.service: product-postgres-db
  name: product-postgres-db

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-postgres-db

  template:
    metadata:
      labels:
        io.kompose.network/services-backend: "true"
        io.kompose.service: product-postgres-db

    spec:
      containers:
        - env:
            - name: PGDATA
              value: /data/product/postgres
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: productpostgresadmin

          image: postgres:latest

          name: productpostgres

          ports:
            - containerPort: 5432
              hostPort: 5432
              
          volumeMounts:
            - mountPath: /data/product/postgres
              name: product

      hostname: postgresproduct
      
      volumes:
        - name: product
          persistentVolumeClaim:
            claimName: product
