import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/UI/Header";
import { Footer } from "@/components/UI/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className="w-screen h-screen overflow-x-hidden">
        <Header isConnected={false}></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
