apiVersion: apps/v1
kind: Deployment

metadata:
  name: franchise-postgres-db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: franchise-postgres-db

  template:
    metadata:
      labels:
        app: franchise-postgres-db

    spec:
      containers:
        - name: franchisepostgres
          env:
            - name: PGDATA
              value: /data/franchise/postgres
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: franchisepostgresadmin

          image: postgres:latest

          resources:
            limits:
              cpu: 100m
              memory: 500Mi

          ports:
            - containerPort: 5432

          volumeMounts:
            - mountPath: /data/franchise/postgres
              name: franchise
      
      volumes:
        - name: franchise
          persistentVolumeClaim:
            claimName: franchise
