apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    io.kompose.service: delivery-host
  name: delivery-host

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: delivery-host

  template:
    metadata:
      labels:
        io.kompose.network/services-backend: "true"
        io.kompose.service: delivery-host

    spec:
      containers:
        - name: DeliveryHost

          env:
            - name: ConnectionStrings__DefaultConnection
              value: '"Server=tcp:postgresdelivery,5433;Initial Catalog=Delivery;Persist Security Info=False;User ID=deliverypostgresadmin;Password=admin;Connection Timeout=30;"'
            - name: RabbitMQ__Hostname
              value: rabbitmq
            - name: RabbitMQ__Password
              value: admin
            - name: RabbitMQ__Username
              value: admin

          image: lutrp/goodfood-deliveryms

          resources:
            limits:
              cpu: 100m
              memory: 200Mi

          ports:
            - containerPort: 8080
              hostPort: 50003
