apiVersion: v1
kind: Service

metadata:
  labels:
    io.kompose.service: delivery-host
  name: delivery-host

spec:
  ports:
    - name: "50003"
      port: 50003
      targetPort: 8080
  selector:
    io.kompose.service: delivery-host
    
status:
  loadBalancer: {}
