apiVersion: apps/v1
kind: Deployment

metadata:
  name: delivery-host

spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-host

  template:
    metadata:
      labels:
        app: delivery-host

    spec:
      containers:
        - name: deliveryhost

          env:
            - name: ConnectionStrings__DefaultConnection
              value: '"Server=tcp:delivery-postgres-db-service,5433;Initial Catalog=Delivery;Persist Security Info=False;User ID=deliverypostgresadmin;Password=admin;Connection Timeout=30;"'
            - name: RabbitMQ__Hostname
              value: rabbitmq-service
            - name: RabbitMQ__Password
              value: admin
            - name: RabbitMQ__Username
              value: admin

          image: lutrp/goodfood-deliveryms

          resources:
            limits:
              cpu: 100m
              memory: 500Mi

          ports:
            - containerPort: 8080