apiVersion: v1
kind: Service

metadata:
  name: delivery-host-service

spec:
  type: NodePort
  ports:
    - name: "50003"
      port: 50003
      targetPort: 8080
      nodePort: 30003
  selector:
    app: delivery-host
