apiVersion: v1
kind: Service

metadata:
  name: rabbitmq-service

spec:
  type: NodePort
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
      nodePort: 30100
  selector:
    app: rabbitmq
