apiVersion: v1
kind: Service

metadata:
  name: rabbitmq-service

spec:
  ports:
    - name: "amqp"
      port: 5672
      targetPort: 5672
    - name: "web"
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
  type: ClusterIP
status:
  loadBalancer: {}
