apiVersion: apps/v1
kind: Deployment

metadata:
  name: franchise-host

spec:
  replicas: 1
  selector:
    matchLabels:
      app: franchise-host

  template:
    metadata:
      labels:
        app: franchise-host

    spec:
      containers:
        - name: franchisehost

          env:
            - name: ConnectionStrings__DefaultConnection
              value: Host=franchise_postgres_db;Port=5432;Database=franchises;Username=franchisepostgresadmin;Password=admin;
            - name: RabbitMQ__Hostname
              value: rabbitmq-service
            - name: RabbitMQ__Password
              value: admin
            - name: RabbitMQ__Username
              value: admin

          image: lutrp/goodfood-franchisems

          resources:
            limits:
              cpu: 100m
              memory: 500Mi

          ports:
            - containerPort: 8080