apiVersion: v1
kind: Service

metadata:
  labels:
    io.kompose.service: auth-host
  name: auth-host

spec:
  ports:
    - name: "50001"
      port: 50001
      targetPort: 8080
  selector:
    io.kompose.service: auth-host
    
status:
  loadBalancer: {}
