apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    io.kompose.service: auth-mongodb
  name: auth-mongodb

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-mongodb

  template:
    metadata:
      labels:
        io.kompose.network/services-backend: "true"
        io.kompose.service: auth-mongodb

    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin

          image: mongo:jammy
          
          name: authentificationmongo

          ports:
            - containerPort: 27017
              hostPort: 27017
              
          volumeMounts:
            - mountPath: /data/auth/mongodb
              name: auth

      hostname: mongodbauth

      volumes:
        - name: auth
          persistentVolumeClaim:
            claimName: auth