version: '3.8'

services:
  host:
    build: ./Sources
    restart: always
    ports:
      - "50003:8080"
    env_file:
      - Sources/.env
      - Sources/compose.env

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"