apiVersion: apps/v1
kind: Deployment

metadata:
  name: delivery-host

spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-host

  template:
    metadata:
      labels:
        app: delivery-host

    spec:
      containers:
        - name: deliveryhost

          env:
            - name: ConnectionStrings__DefaultConnection
              value: Host=delivery-postgres-db-service;Port=5501;Database=delivery;Username=deliverypostgresadmin;Password=admin;
            - name: RabbitMQ__Hostname
              value: rabbitmq-service
            - name: RabbitMQ__Password
              value: admin
            - name: RabbitMQ__Username
              value: admin

          image: lutrp/goodfood-deliveryms
          imagePullPolicy: "Always"
          
          resources:
            limits:
              cpu: 100m
              memory: 500Mi

          ports:
            - containerPort: 8080