apiVersion: v1
kind: Service

metadata:
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "50000"
      port: 50000
      targetPort: 8080
  selector:
    io.kompose.service: api-gateway
    
status:
  loadBalancer: {}
