apiVersion: v1
kind: Service

metadata:
  name: api-gateway-service
spec:
  type: NodePort
  ports:
    - name: "50000"
      port: 50000
      targetPort: 8080
      nodePort: 30000
  selector:
    app: api-gateway
